version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: dvf-postgres
    environment:
      POSTGRES_DB: dvf
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: