DVF_COLUMN_MAPPING = {
    'Identifiant de document': 'identifiant_document',
    'Reference document': 'reference_document',
    '1 Articles CGI':'article_cgi_1',
    '2 Articles CGI':'article_cgi_2',
    '3 Articles CGI':'article_cgi_3',
    '4 Articles CGI':'article_cgi_4',
    '5 Articles CGI':'article_cgi_5',
    'No disposition':'no_disposition',
    'Date mutation':'date_mutation',
    'Nature mutation':'nature_mutation',
    'Valeur fonciere':'valeur_fonciere',
    'No voie':'no_voie',
    'B/T/Q':'btq',
    'Type de voie':'type_de_voie',
    'Code voie':'code_voie',
    'Voie':'voie',
    'Code postal':'code_postal',
    'Commune':'commune',
    'Code departement':'code_departement',
    'Code commune':'code_commune',
    'Prefixe de section':'prefixe_de_section',
    'Section':'section',
    'No plan':'no_plan',
    'No Volume':'no_volume',
    '1er lot':'lot_1',
    'Surface Carrez du 1er lot':'surface_carrez_lot_1',
    '2eme lot':'lot_2',
    'Surface Carrez du 2eme lot':'surface_carrez_lot_2',
    '3eme lot':'lot_3',
    'Surface Carrez du 3eme lot':'surface_carrez_lot_3',
    '4eme lot':'lot_4',
    'Surface Carrez du 4eme lot':'surface_carrez_lot_4',
    '5eme lot':'lot_5',
    'Surface Carrez du 5eme lot':'surface_carrez_lot_5',
    'Nombre de lots':'nombre_de_lots',
    'Code type local':'code_type_local',
    'Type local':'type_local',
    'Identifiant local':'identifiant_local',
    'Surface reelle bati':'surface_reelle_bati',
    'Nombre pieces principales':'nombre_pieces_principales',
    'Nature culture':'nature_culture',
    'Nature culture speciale':'nature_culture_speciale',
    'Surface terrain':'surface_terrain',
}

