CREATE TABLE raw_dvf (
    -- Métadonnées techniques
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP DEFAULT NOW(),
    is_valid BOOLEAN,
    reject_reason VARCHAR(255),
    
    -- Colonnes du fichier DVF
    identifiant_document VARCHAR(50),
    reference_document VARCHAR(50),
    article_cgi_1 VARCHAR(10),
    article_cgi_2 VARCHAR(10),
    article_cgi_3 VARCHAR(10),
    article_cgi_4 VARCHAR(10),
    article_cgi_5 VARCHAR(10),
    no_disposition VARCHAR(50),
    date_mutation DATE,
    nature_mutation VARCHAR(100),
    valeur_fonciere DECIMAL(15,2),
    no_voie VARCHAR(10),
    btq VARCHAR(1),
    type_de_voie VARCHAR(50),
    code_voie VARCHAR(10),
    voie VARCHAR(255),
    code_postal VARCHAR(5),
    commune VARCHAR(255),
    code_departement VARCHAR(3),
    code_commune VARCHAR(5),
    prefixe_de_section VARCHAR(10),
    section VARCHAR(10),
    no_plan VARCHAR(10),
    no_volume VARCHAR(10),
    lot_1 VARCHAR(10),
    surface_carrez_lot_1 DECIMAL(10,2),
    lot_2 VARCHAR(10),
    surface_carrez_lot_2 DECIMAL(10,2),
    lot_3 VARCHAR(10),
    surface_carrez_lot_3 DECIMAL(10,2),
    lot_4 VARCHAR(10),
    surface_carrez_lot_4 DECIMAL(10,2),
    lot_5 VARCHAR(10),
    surface_carrez_lot_5 DECIMAL(10,2),
    nombre_de_lots INT,
    code_type_local VARCHAR(10),
    type_local VARCHAR(50),
    identifiant_local VARCHAR(50),
    surface_reelle_bati DECIMAL(10,2),
    nombre_pieces_principales INT,
    nature_culture VARCHAR(50),
    nature_culture_speciale VARCHAR(50),
    surface_terrain DECIMAL(15,2)
);